version: '3.8'
services:
    redis_db:
        image: 'redis'
        ports:
            - '6399:6379'
        expose:
            - 6379
        restart: always
    api:
        container_name: ts-express-boilerplate
        build:
            context: ./
            dockerfile: Dockerfile.dev
            target: dev
        volumes:
            - .:/app
        command: sh -c "npm i && npm run dev"
        ports:
            - '4001:8080'
        environment:
            NODE_ENV: development
            DEBUG: nodejs-docker-express:*
